### ISSUE TITLE
[Question]  `historical_forecasts` with `retrain=False`

### ISSUE THREAD

**Issue by david-vicente** [unit8co/darts#679]
In the docstring for the method `historical_forecasts` belonging to the class `ForecastingModel` it is mentioned that:

> If `retrain` is set to False (useful for models for which training might be time-consuming, such as
> deep learning models), the model will only be trained on the initial training window
> (up to `start` time stamp), **and only if it has not been trained before**.

However I can not find the code that ensures the "**and only if it has not been trained before**" part.

**Comment by pennfranc** [comment]
Actually it seems that fit was not being called at all when `retrain` was set to `False`. I think #681 should fix it, feel free to take a look

**Comment by david-vicente** [comment]
Looks good. I wasn't sure if it was a problem with the code or with the docstring.

**Comment by hrzn** [comment]
Good catch!

**Comment by pennfranc** [comment]
PR is merged.

**Comment by wassimzerouati** [comment]
Hello, I don't see the PR change on any deployed version ; hence I still have the issue. (Doing the fix on my local works though).
